export const CATEGORIA_LIST = [
    "Combos",
    "SmartWatchs",
    "Caixas De Som",
    "Eletronicos",
    "Salão e Barbearia",
    "Automotivos",
    "Videgame",
    "Computador",
    "Ferramentas",
    "Brinquedos",
    "Relogios",
    "Headset e Fones",
    "Luzes e iluminação",
    "Cameras",
    "Oculos",
    "Celulares",
    "Capinhas",
    "Piscinas",
    "Microfones",
    "Petshop",
    "Tv e acessorios",
    "Cabos",
    "Roupas",
    "Boné e chapeu",
    "Calçados",
    "Roupa infantil",
    "Calçado infantil",
    "Bebê e mamãe",
    "Cama, mesa e banho",
    "Saúde e beleza",
    "Instrumentos musicais",
    "Moveis",
    "Decoração",
    "Fantasia",
    "Esportivos",
    "Malas e bolsas",
    "Livraria e papelaria",
    "Caça e pesca",
    "Agrorural",
    "Alianças",
    "Bijuterias",
    "Piscinas",
    "Adaptadores",
    "Inversores",
    "Maquiagem",
    "Cosmeticos",
    "Perfumes",
    "Drones",
    "Ventiladores",
    "Linha e costura",
    "Panelas"
];